# generated by Neptune Namespaces v0.3.0
# file: tests/art/web_gl/namespace.coffee

Art = require '../namespace'
module.exports = Art.WebGl ||
Art.addNamespace 'WebGl', class WebGl extends Neptune.Base
  ;